django-OTS/myproject/OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'

urlpatterns = [
    path('', welcome, name='welcome-page'),
    path('registration/', candidateRegistrationForm, name='register-form'),
    path('store-candidate/', candidateRegistration, name='storeCandidate'),
    path('login/', loginView , name="login"),
    path('home/', candidateHome , name="home"),
    path('test-paper/', testPaper , name="testpaper"),
    path('calculate-result/', calculateTestResult , name="calculateTest"),
    path('test-history/', testResultHistory , name="testHistory"),
    path('result/', showTestResult , name="result"),
    path('logout/', logoutView , name="logout"),
]

django-OTS/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('OTS/', include('OTS.urls')),
    path('admin/', admin.site.urls),
]

django-OTS/myproject/OTS/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    username=models.CharField(primary_key=True , max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=20)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
    
class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=255)

    
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True, auto_created=True)
    username=models.ForeignKey(Candidate, on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()

django-OTS/myproject/OTS/views.py
from django.shortcuts import render,redirect
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
import random

# Create your views here.
def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())

def candidateRegistrationForm(request):
    return render(request,'registration_form.html')

def candidateRegistration(request):
    if request.method=='POST':
        # isf user exist already
        username=request.POST['username']
        if(len(Candidate.objects.filter(username=username))):
            userStatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2
    else:
        #request method is not post
        userStatus=3
    context={
        'userStatus':userStatus
    }
    return render(request, 'registration.html' , context)

def loginView(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        candidate = Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError='Invalid username or password '
            res=render(request,'login.html' ,{'loginError':loginError})
        else:
            #login success
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("/OTS/home")

    else:
        res =render(request, 'login.html' )
    return res



def candidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('/OTS/login')
    else:
        res = render(request ,'home.html')
    return res

def testPaper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('/OTS/login')
    # fetching questions from database table
    n=int(request.GET['n'])
    questions=list(Question.objects.all())
    # shuffling questions
    random.shuffle(questions)
    # limiting questions to n
    questions=questions[:n]
    context={
        'questions':questions
    }
    return render(request, 'test_paper.html', context)


def calculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('/OTS/login')
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int(request.POST[k]))
    for n in qid_list:
        question = Question.objects.get(qid=n)
        try:
            ans=request.POST[f'q{n}']
            if ans==question.ans:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except Exception as e:
            print(e)
    points=(total_right-total_wrong)/len(qid_list)*10
    #store result in result table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    #update candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return redirect('/OTS/result')
    #render result page with result details
    # context={
    #     'total_attempt':total_attempt,
    #     'total_right':total_right,
    #     'total_wrong':total_wrong,
    #     'points':points
    # }
    # return render(request,'result.html', context)




def testResultHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('/OTS/login')
    # fetch all result from result table
    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username=candidate[0].username)
    context={
        'candidate':candidate[0],
       'results':results
    }
    return render(request,'result_history.html', context)

def showTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect('/OTS/login')
    # fetch latest result from result table
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid, username=request.session['username'])
    context={
       'result':result
    }
    return render(request,'show_result.html', context)
 
def logoutView(request):
    if 'username' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect('/OTS/login')

django-OTS/myproject/OTS/templates/home.html
{% extends "main.html" %}

{% block title %}Candidate Home Page{% endblock title %}
{% block top %}
<a href="{% url 'OTS:home' %}"> Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock top %}

{% block content %}
<h1>Welcome {{request.session.name}}, to your home page.</h1>
<div class="button-link">
    <a href="{% url 'OTS:testpaper' %}?n=1">Test of 1 Question</a>
</div>
<div class="button-link">
    <a href="{% url 'OTS:testpaper' %}?n=3">Test of 3 Question</a>
</div>
<div class="button-link">
       <a href="{% url 'OTS:testpaper' %}?n=5">Test of 5 Question</a>
</div>

<div class="button-link">
     <a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>

{% endblock content %}

django-OTS/myproject/OTS/templates/login.html
{% extends "main.html" %}

{% block title %}OTs - Login Form {% endblock title %}
{% block top %}
<a href="{% url 'OTS:register-form' %}">Sign Up</a>
{% endblock top %}

{% block content %}
<h3>Login</h3>
<div class="all-forms">
    {% if loginError %}
        <div id="error">{{loginError}}</div>
    {% endif %}
    <form action="{% url 'OTS:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-unit">
            <label for="username">Username</label>
            <input type="text" name="username">
        </div>
        <div class="form-unit">
            <label for="password">Password</label>
            <input type="password" name="password">
        </div>
        <div class="form-unit">
            <input type="submit" value="Login" class="login">
            <input type="reset" value="Clear" class="clear">
        </div>
    </form>
    <p>New User <a href="{% url 'OTS:register-form' %}">Click Here</a></p>
</div>

{% endblock content %}

django-OTS/myproject/OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock  %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'theme.css' %}">
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>Online Testing System</h1></div>
        <div class="menu">
            {% block top %}        
            {% endblock top %}
        </div>
    </div>
    <div class="content">
        {% block content %}   
        {% endblock content %}
    </div>
    
</body>
</html>

django-OTS/myproject/OTS/templates/registration.html
{% extends "main.html" %}

{% block title %}OTS- Registration Satus{% endblock title %}
{% block top %}
<a href="{% url 'OTS:register-form' %}">Sign Up</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock top %}

{% block content %}
{% if userStatus == 1 %}
    <div class="userSatus">
        Sorry, Username already exists, please try diffenrent username.
        <a href="{% url 'OTS:register-form' %}"> Back To Candidate Registration Form</a>
    </div>
{% elif userStatus == 2 %}
    <div class="userSatus">
        Congratulations!!, User created successfully.
        <a href="{% url 'OTS:login' %}">Login</a>
    </div>
{% elif userStatus == 3 %}
     <div class="userSatus">
        Oops!!, Improper Request.
        <a href="{% url 'OTS:register-form' %}"> Back To Candidate Registration Form</a>
    </div>
{% endif %}

{% endblock content %}


django-OTS/myproject/OTS/templates/registration_form.html
{% extends "main.html" %}

{% block title %}OTS Registration Form{% endblock title %}
{% block top %}
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock top %}

{% block content %}
<h3>Sign Up</h3>
<div class="all-forms">
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username">
        <label for="password">Password</label>
        <input type="password" name="password">
        <label for="name">Name</label>
        <input type="text" name="name">

        <input type="submit" value="Submit">
        <input type="reset" value="Clear">
    </form> 
    <p>already have an account <a href="{% url 'OTS:login' %}">Click Here</a></p>
</div>


{% endblock content %}

django-OTS/myproject/OTS/templates/result_history.html
{% extends "main.html" %}

{% block title %}OTS - Candidate Result History{% endblock title %}
{% block top %}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock top %}

{% block content %}
<h1>Report Card</h1>
<p>Hi {{candidate.name}}, you have attempted in total {{candidate.test_attempted}} test and 
you have scored {{candidate.points}} on the scale of 10.
</p>
<table>
    <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Attempt</th>
    <th>Right</th>
    <th>Wrong</th>
    <th>Points</th>
    </tr>
    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

django-OTS/myproject/OTS/templates/show_result.html
{% extends "main.html" %}

{% block title %}OTS - Test Results{% endblock title %}
{% block top %}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock top %}

{% block content %}
<p>Result Page</p>
<table>
    <tr>
    <th>Date</th>
    <th>Time</th>
    <th>Attempt</th>
    <th>Right</th>
    <th>Wrong</th>
    <th>Points</th>
    </tr>
    {% for r in result %}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

django-OTS/myproject/OTS/templates/test_paper.html
{% extends "main.html" %}

{% block title %}OTS - Testpaper{% endblock title %}
{% block top %}
{% endblock top %}

{% block content %}
    <h1>Welcome {{ request.session.name }}, to your test paper.</h1>
    <form action="{% url 'OTS:calculateTest' %}" method="post">
        {% csrf_token %}
        {% for question in questions %}
        <div class="question">
            <input type="hidden" name="qno{{question.qid}}" value="{{ question.qid }}">
            {{ question.que}}
        </div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="a">{{question.a}}</div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>
        <div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div>
        {% endfor %}
        <input type="submit" value="Submit">
    </form>


{% endblock content %}

django-OTS/myproject/OTS/templates/welcome.html
{% extends "main.html" %}

{% block title %}Welcome To Online Testing System{% endblock title %}
{% block top %}
<a href="{% url 'OTS:register-form' %}">Sign Up</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock top %}

{% block content %}
<p>Welcome to oline Testing Platform </p>

{% endblock content %}